// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXlp1gd4n9nhxqw9-jKBYBlU3MtaizRI8',
    appId: '1:469752390363:web:d836c0ada46657dd0962fe',
    messagingSenderId: '469752390363',
    projectId: 'grinch-flutter1',
    authDomain: 'grinch-flutter1.firebaseapp.com',
    storageBucket: 'grinch-flutter1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutp1k5uLKkdxm01pIv7e741MCwJ-hR8o',
    appId: '1:469752390363:android:4832401ce83a94ba0962fe',
    messagingSenderId: '469752390363',
    projectId: 'grinch-flutter1',
    storageBucket: 'grinch-flutter1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjBf9FwGzICl-soEb5_PG1Oh6UizGoOUg',
    appId: '1:469752390363:ios:7b22011849f512ec0962fe',
    messagingSenderId: '469752390363',
    projectId: 'grinch-flutter1',
    storageBucket: 'grinch-flutter1.firebasestorage.app',
    iosBundleId: 'com.grinch.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjBf9FwGzICl-soEb5_PG1Oh6UizGoOUg',
    appId: '1:469752390363:ios:7b22011849f512ec0962fe',
    messagingSenderId: '469752390363',
    projectId: 'grinch-flutter1',
    storageBucket: 'grinch-flutter1.firebasestorage.app',
    iosBundleId: 'com.grinch.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXlp1gd4n9nhxqw9-jKBYBlU3MtaizRI8',
    appId: '1:469752390363:web:16f55253614e1a210962fe',
    messagingSenderId: '469752390363',
    projectId: 'grinch-flutter1',
    authDomain: 'grinch-flutter1.firebaseapp.com',
    storageBucket: 'grinch-flutter1.firebasestorage.app',
  );
}
